spring:
  ai:
    mcp:
      server:
        name: author-tool-server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/messages
        stdio: false

server:
  port: 8088

logging:
  level:
    org:
      springframework:
        ai: DEBUG